title: 10 Dias De Python con IA
description: Una gu√≠a de inicio r√°pido para programadores de Vibe sin experiencia en codificaci√≥n
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# External navigation links
nav_external_links:
  - title: "üêç EJEMPLOS DE C√ìDIGO EN PYTHON"
    url: https://github.com/StructuralWizard/10DiasDePython_es.github.io/tree/main/_python_code
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false


# collections:
#   python_code:
#     output: true

# just_the_docs:
#   collections:
#     python_code:
#       name: Python Code
#       description: Python code examples for the 10 Days of Code
#       nav_exclude: false # to exclude the entire collection from the main navigation
#       nav_fold: false # to fold the collection, instead of showing links to all its top-level pages2
#       search_exclude: false # to exclude all the collection pages from search results
#   # For copy button on code
#   enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.6.0"
  # for (v10+)
  path: "/assets/js/mermaid.esm.min.mjs"
  #path: "./node_modules/mermaid/dist/mermaid.esm.min.mjs"
  # for (<v10):
  # path: "/assets/js/mermaid.min.js"
  # Note: copy both `mermaid.esm.min.mjs` (v10+) or `mermaid.min.js` (<v10) and the associated
  # `.map` file from the specified version of `mermaid/dist` to `/assets/js/`.

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Exclude files from processing
exclude:
  - "**/*.xlsm"
  - "**/*.xlsx"
  - "**/*.xls"
  - "**/*.pdf"
  - "**/*.doc"
  - "**/*.docx"
  - "**/*.pptx"
  - "**/*.ppt"
  - "**/slides/*.xlsm"
  - "**/slides/*.xlsx"
  - "**/slides/*.xls"
  - "**/slides/*.pdf"
  - "**/slides/*.doc"
  - "**/slides/*.docx"
  - "**/slides/*.pptx"
  - "**/slides/*.ppt"
  - "docs/Day1/slides/alignme.xlsm"
  - node_modules/
  - vendor/
